default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build debug APK"
  lane :build_debug do
    gradle(
      task: "assemble",
      build_type: "Debug"
    )
  end

  desc "Build release APK"
  lane :build_release do
    gradle(
      task: "assemble",
      build_type: "Release"
    )
  end

  desc "Deploy a new version to the Google Play (Internal Testing)"
  lane :deploy_internal do
    gradle(
      task: "bundle",
      build_type: "Release"
    )
    upload_to_play_store(
      track: "internal",
      skip_upload_metadata: false,
      skip_upload_images: false,
      skip_upload_screenshots: false
    )
  end

  desc "Deploy a new version to the Google Play (Beta)"
  lane :deploy_beta do
    gradle(
      task: "bundle",
      build_type: "Release"
    )
    upload_to_play_store(
      track: "beta",
      skip_upload_metadata: false,
      skip_upload_images: false,
      skip_upload_screenshots: false
    )
  end

  desc "Deploy a new version to the Google Play (Production)"
  lane :deploy_production do
    gradle(
      task: "bundle",
      build_type: "Release"
    )
    upload_to_play_store(
      track: "production",
      skip_upload_metadata: false,
      skip_upload_images: false,
      skip_upload_screenshots: false
    )
  end

  desc "Take screenshots"
  lane :screenshots do
    gradle(task: "assemble assembleAndroidTest")
    screengrab(
      app_package_name: "com.autodiag.ai",
      tests_package_name: "com.autodiag.ai.test",
      locales: ["en-US", "ru-RU"],
      clear_previous_screenshots: true,
      app_apk_path: "app/build/outputs/apk/debug/app-debug.apk",
      tests_apk_path: "app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk"
    )
  end
end
